### ISSUE TITLE
want to contribute a web development project

### ISSUE THREAD

**Issue by Jatingupta9120** [CodeNest-Studio/Web-Dev-Projects#6]
plz assign this issue to me under hacktoberfest2023

**Comment by Harshit-Raj-14** [comment]
There is no need to open an issue you can start adding your web dev projects here.
Just adhere to the proper way of uploading project like adding a readme file and an deployment link to your project.

**Comment by Jatingupta9120** [comment]
Bhai phir wo hacktoberfesr m count hoga ?

**Comment by Harshit-Raj-14** [comment]
@Jatingupta9120 Yes it will be accepted. Many have already contributed. There's still time.

**Comment by Jatingupta9120** [comment]
ye to closed krdia

**Comment by Harshit-Raj-14** [comment]
@Jatingupta9120 I am saying you can directly make a PR of your project to be added in the repo. No need to raise issues.
